### ISSUE TITLE
ActivityParty entities are not created and assigned to Activity

### ISSUE THREAD

**Issue by catalin-ilie** [delegateas/XrmMockup#84] opened 2019-10-14 11:32 UTC
**Describe the bug**
If i create an Activity entity (i.e. PhoneCall with From and To), ActivityParty related entities are not created, properties are null at retrieve

**Comment by magesoe** [comment] 2019-10-14 12:08
That is correct, it is also mentioned in #83

**Comment by misoeli** [comment] 2021-06-11 11:10
As mentioned, duplicate of #83. Closing here

**Closed by misoeli** 2021-06-11 11:10 UTC

**Comment by krihvi** [comment] 2021-08-11 12:54
Note that this is slightly different. #83 was focused on AcitvityPointer, ActivityParty, which is another activity related entity Mockup dosen't support currently. I recommend you either expand scope of #83 or reopen this ticket.

**Comment by krihvi** [comment] 2021-08-11 13:25
In CRM when an activity is created with values in any of the standard ActivityParty fields, it create a number of ActivityParty Records to store the information. Much of this information is only stored on the activityParties and not on the entity, as MockUp believes.
This seems to be MS Using some front end code to lookup in the activity party table and make it look like a MultiLookup field.

Mockup Should parse the 11 fields on activities and create the relevant ActivityParty:

Sender | 1 | Specifies the sender.
ToRecipient | 2 | Specified the recipient in the To field.
CCRecipient | 3 | Specifies the recipient in the Cc field.
BccRecipient | 4 | Specifies the recipient in the Bcc field.
RequiredAttendee | 5 | Specifies a required attendee.
OptionalAttendee | 6 | Specifies an optional attendee.
Organizer | 7 | Specifies the activity organizer.
Regarding | 8 | Specifies the regarding item.
Owner | 9 | Specifies the activity owner.
Resource | 10 | Specifies a resource.
Customer | 11 | Specifies a customer.

https://promx.net/en/2020/01/how-to-retrieve-an-activity-party-list-in-microsoft-dynamics-365-using-web-api/
